on: [push]

name: Test okteto actions log-level

jobs:

  devflow:
    runs-on: ubuntu-latest
    steps:
    - name: Context
      uses: okteto/context@cb3a59a25486a67dffd6c1d3a590c1c405c43d39
      with:
        url: ${{ secrets.OKTETO_URL }}
        token: ${{ secrets.OKTETO_TOKEN }}
        log-level: warn

    - name: "Okteto Deploy Preview Action"
      uses: okteto/deploy-preview@a0d66816a35be82253a73d46861a511a8ad61da9
      with:
        name: teresaromero-preview
        log-level: warn
    
    - name: "Okteto Destroy Preview Action"
      uses: okteto/destroy-preview@3f45e628352325d94d728e4207699c75b51340bc
      with:
        name: teresaromero-preview
        log-level: warn
    
    - name: "Okteto Create Namespace Action"
      uses: okteto/create-namespace@d420f34a7fea85baaf3d111b6b3a2477c102ad85
      with:
        namespace: teresaromero-action-ns
        log-level: warn
    
    - name: "Okteto Namespace Action"
      uses: okteto/namespace@b7824ae8a99d415b3defa4cad695e374627f01d6
      with:
        namespace: teresaromero-teresaromero
        log-level: warn

    - name: "Okteto Delete Namespace Action"
      uses: okteto/delete-namespace@73e1c6d272bf53f9f2271189d8eed04630b957b4
      with:
        namespace: teresaromero-action-ns
        log-level: warn

    # - name: "Okteto Build Action"
    #   uses: okteto/build@c466eb2cbdbff91cbd954dbaea7b429402e706be
    #   with:
    #     tag: okteto.dev/go-getting-started
    #     log-level: warn

    - name: "Okteto Pipeline Action"
      uses: okteto/pipeline@855e283a35ba2dc775f1977b26f8359443c150db
      with:
        name: teresaromero-pipeline
        log-level: warn

    - name: "Okteto Destroy Pipeline Action"
      uses: okteto/destroy-pipeline@8a6b388c78734478694c3296968a28830b3734b1
      with:
        name: teresaromero-pipeline
        log-level: warn

    - name: "Okteto Test Action"
      uses: okteto/test@934839dfc81c53a50d898e27c9e9277f416b8cfb
      with:
        log-level: warn
